<template>
  <div class="container">
    <div class="main-content">
      <div class="chat-area">
        <div class="chat-card userchat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card aichat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card userchat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card aichat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div><div class="chat-card userchat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card aichat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card userchat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card aichat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card userchat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>
        <div class="chat-card aichat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div><div class="chat-card userchat">texzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzttexzt</div>      
      </div>
    </div>

    <div class="search-content footer-fix">
      <input class="input01" type="text" placeholder="메시지를 입력하세요" />
      <button class="btn01 ml-5">전송</button>
    </div>
  </div>
</template>

<script setup>
import "@/assets/css/global.scss";
</script>

<style>
</style>
